### ISSUE TITLE
Import LAB files from Sonic Visualiser

### ISSUE THREAD

**Issue by stefan-balke** [marl/jams#107]
Hey folks,

when exporting lab-files from Sonic Visualiser (use *.txt for this instead of *.csv),
they export in this structure:
#start_time \t #value \t #duration \t #label

A typical call would then be:

`jams.util.import_lab('segment_open', names=range(4), usecols=[0, 2, 3], sep='\t')`

but I can't overwrite the behaviour that the duration is calculated.

So maybe we could add a flag in the function call to disable this?

**Comment by stefan-balke** [comment]
Found related work here:
https://github.com/urinieto/msaf/blob/master/datasets/Sargon/scripts/CSV%20to%20JAMS.ipynb

**Comment by bmcfee** [comment]
Sorry for the lag on this one --

Can you gist an example file so we have something concrete to refer to?

I think I don't understand your proposed call signature.

More generally speaking, if you have an unusual format that needs some hand-holding while parsing, I'd recommend turning into a dataframe and then doing something like this:

```python
df = process_file_to_dataframe(filename)
annotation.data = jams.JamsFrom.from_dataframe(df)
```

But I agree that if SV is outputting in a consistent way that doesn't work, we should fix it so that it's easy to import.

**Comment by stefan-balke** [comment]
Yup, looks like this:

```
0.232199546	5	57.028208616	Theme, tp, ts
57.260408163	5	54.938412698	Solo_1, tp
112.198820861	6	55.402811791	Solo_1, tp
167.601632653	6	56.192290249	Solo_2, ts
223.793922902	6	56.888888888	Solo_3, p
280.682811791	6	56.610249433	Solo_4, ts, tp, perc
337.240816326	7	54.661224489	Solo_5, perc
391.859954648	7	57.492607709	Theme, tp, ts
449.352562358	5	12.399455782	ending
```

Only thing I'm calling here is having start + duration instead of start + end as a flag.

**Comment by bmcfee** [comment]
Picking this up again:

Would it suffice to add a flag `infer_duration=True` that does the `end-start` logic when set, and otherwise propagates the second time-like column?

Everything else seems to be well handled by pandas (usecols, etc).
