### ISSUE TITLE
Support Decimal format/Quantization

### ISSUE THREAD

**Issue by faroit** [marl/jams#181]
I have an application where a loss in precision for encoding an annotation value is highly desirable because it would significantly reduce the filesize of the json output. Unfortunately, pythons builtin in json encoder does not support decimal numbers natively. Therefore the following example fails:

```python
from decimal import Decimal as D
ann.append(time=0.33, duration=0.0, value=D(D(np.pi).quantize(D('.001'))))
```

with `TypeError: Object of type 'Decimal' is not JSON serializable`.

One way to fix this would be to allow to use custom json encoder [like this](https://gist.github.com/iancoleman/4536693). However, I don't know if that would be accessible for users in jams.

Another way would be to switch to [simplejson](https://github.com/simplejson/simplejson) which does support decimal data natively. Also it can be used as a drop in replacement for everything in jams and has no further dependencies.

**Comment by bmcfee** [comment]
Thanks @faroit for raising this one.  It's an interesting and nontrivial problem.

One question I might ask up front: if you want an easy way to reduce file size, you can always export to `jamz` (gzipped-jams).  You gain significantly in file size, preserve accuracy, but lose human readability.  Not an ideal solution in all scenarios, but it might work for you.

Otherwise, a couple of things to consider:

- As long as we produce valid json, anything we do to the encoder (including custom/extended encoder classes) is fair game.
- I wouldn't want to use custom data types to enforce quantization (Eg `decimal`), but if we could quantize on output by an optional kwarg, that'd be fine.  I'm thinking something like `jams.save(..., precision=3)` that gets threaded through all the encoding.
- I'm not sure about simplejson, since the performance hit seems to be significant.  See [benchmarks].
- I generally suspect that the desire for this particular feature is somewhat limited -- I for one always err on the side of precision, since disk is cheap, and you can always simplify the data when displaying to a user without permanently discarding anything.  If you really want this kind of compression, it might be best to write a separate utility that post-processes json files to reduce numerical precision.

**Comment by justinsalamon** [comment]
fwiw, I once had an issue where `json.dump()` would actually crash when trying to serialize a high precision float, and the solution was to use `round(x, 15)` to limit the float to 15 decimals. So that might be a different reason to support a precision kwarg, although I have to say since then I haven't re-encountered this issue.

**Comment by bmcfee** [comment]
> fwiw, I once had an issue where json.dump() would actually crash when trying to serialize a high precision float,

That sounds like a json implementation error, and definitely above our pay grade (ie, tag-as-won't-fix).

**Comment by faroit** [comment]
In the end [I went with](https://github.com/sigsep/sigsep-mus-eval/blob/master/tests/data/Music%20Delta%20-%20Rock.json) Decimal and simplejson. Performance was not an issue. 
I like jams, but I wanted to have as little overhead as possible. 

Anyway, thanks for the help!
