### ISSUE TITLE
Version 2 Design Considerations

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#2]
Following the presentation and discussion at / after ISMIR2014, a variety of ideas have been flying around regarding next steps and possible improvements to JAMS:
- "Group-by-task" versus "explicit typing", or somewhere in between
- Namespaces for interpreting the meaning of observations
- "One general type with conditional validation" versus "Many specific types with singular validation"
- How, if at all, should this interface with linked data?
- How, if at all, should this be influenced / consistent with the MPEG-7 specification?
- What is the value / goal of readability in the raw JSON?
- JAMS Quick Look: "Text editors" versus "specialized tools"

These are the high-level ones, and I'd like this issue to simply sponge topics for posterity; each individual topic should probably be broken out as separate conversations.

**Comment by bmcfee** [comment]
Now would probably be a good time to circle back on this thread, since the pandas branch is nearly stable.

> "Group-by-task" versus "explicit typing", or somewhere in between
> Namespaces for interpreting the meaning of observations

I think the latter (namespaces) now solves the former (grouping).  We now have a single flat annotation list at the top level, no grouping, but each annotation specifies its namespace.  The query engine makes it possible to slice out annotations by "type", essentially creating groupings on the fly.

> "One general type with conditional validation" versus "Many specific types with singular validation"

Validation is now a two-stage process.  The JAMS schema specifies a single annotation type, and does not interpret the values.  Namespace schemas provide the validation functionality within an annotation.

As a concrete example, all annotations are now arrays of `(time, duration, value, confidence)`, and this is enforced by the JAMS schema.  The JAMS schema also requires that `time` and `duration` be sane (non-negative numbers), but provides no checks for value or confidence, which is the job of the namespace validator.  

> How, if at all, should this interface with linked data?

I think the identifiers sandbox in the metadata does a sufficient job of this, without getting bogged down in the details or providing explicit hooks for every possible linkage.

There might be some opportunities for expanding namespaces in this direction.  I'm thinking specifically for tag vocabularies, it might be useful to have a way of linking/aligning across different namespaces.

> How, if at all, should this be influenced / consistent with the MPEG-7 specification?

Anyone more familiar with mpeg-7 want to chime in?

> What is the value / goal of readability in the raw JSON?

It's nice to have, but shouldn't be our main requirement.  FWIW, I find https://github.com/marl/jams/blob/pandas/datasets/SMC_MIREX/SMC_001.jams to be totally readable, if a bit more verbose than the original lab file(s).

> JAMS Quick Look: "Text editors" versus "specialized tools"

There are loads of json editors out there, and some even accept schema!  Check out http://jeremydorn.com/json-editor/ (https://github.com/jdorn/json-editor)  I bet it wouldn't be hard to fork that one to do dynamic namespace validation as well.
