### ISSUE TITLE
Security flaw in JSON deserialization

### ISSUE THREAD

**Issue by ejhumphrey** [marl/jams#22]
This had occurred to me recently, and finally remembered to mention it. There's a pretty big security flaw in JSON deserialization: https://github.com/marl/jams/blob/pandas/pyjams/pyjams.py#L749

For example (don't load):

```
{
    "object_type": "import os;os.system('rm -rf ~/')"
}
```

One fix is to register objects in the module with a dictionary, and then deserialize through look-ups in that dictionary; all the functionality you want with none of the SQL-injection style hakz.

**Comment by bmcfee** [comment]
Derp, I also noticed that we're double-defining `load()` and `save()` here.  I can take a stab at fixing this if you don't want to deal.

**Comment by bmcfee** [comment]
Actually, I'm even more confused.  Why do we need this context manager?  What's wrong with simply doing `jam = JAMS(**json.load(open(filename)))` ?  It seems to work when I test it that way.

**Comment by bmcfee** [comment]
(recap conversation with @ejhumphrey at dr @urinieto 's shindig)

* Context manager is unnecessary on load, since all objects get passed through the object constructors.
* Context manager is necessary on save, in order to pull out the `__json__` property for each object within a JAMS.

I think we can resolve this as follows:

* Ignore the context manager on load.
* Turn save into a JAMS class method that explicitly retrieves the `__json__` attribute, rather than relying on callbacks/mangling the json object.

**Comment by bmcfee** [comment]
@ejhumphrey please check through this last revision and make sure I didn't do anything insane.

**Comment by bmcfee** [comment]
![later](http://images.wikia.com/spongebob/images/d/de/3000yearslater.jpg)

**Comment by bmcfee** [comment]
Now that we've all completely forgotten everything that happened in this thread: is it still an issue?  Can we close it?

**Comment by urinieto** [comment]
Totally, no idea what this thread was about.

**Comment by bmcfee** [comment]
Well, we no longer have any `eval()` calls, and everything still works, so I think it's set.  I was mainly waiting for the okay from @ejhumphrey before closing out.
