### ISSUE TITLE
Fix annotations in import_lab?

### ISSUE THREAD

**Issue by urinieto** [marl/jams#36]
I am trying to use [import_lab](https://github.com/marl/jams/blob/develop/jams/util.py#L24-L95), but there are some files in the Isophonics dataset that have empty range annotations (e.g., `chordlab/Carole King/06 Way Over Yonder.lab`). This causes the JAMS validation to fail.

So, my question is: should we modify `import_lab` to such that it "fixes" these annotations or should this function not alter the lab at all  (and maybe modify the "broken" annotations in the parsers)?

I would go for the former, and maybe raise a warning every time an alteration of the original lab occurs.

**Comment by bmcfee** [comment]
> This causes the JAMS validation to fail.

This is exactly what vaildation is for. :)

My thoughts on this:

* Core jams io functions should never change/fix the data, beyond what is necessary to correctly parse it.  (Ragged tab split-joining, i think, doesn't count as modification here; rather it's a workaround to deal with poorly specified annotation formats.)
* It's pretty well-known at this point that isophonics has tons of broken timing data.  Correcting this should be the job of the dataset parse script, so that all changes that occur during translation are centralized and properly documented.  (Documentable?)
* Warnings for this kind of thing are bad news, since they're so easy to ignore.  In general, I'd prefer exceptions unless explicitly disabled (eg, `strict=False`).

**Comment by bmcfee** [comment]
Following up: is there anything that needs doing on this issue?

**Comment by urinieto** [comment]
No, I believe we can close this.
