### ISSUE TITLE
jams.load not working?

### ISSUE THREAD

**Issue by urinieto** [marl/jams#47]
I tried to use `jams.load` on [this](https://github.com/marl/jams-data/blob/master/datasets/Isophonics/The%20Beatles/03_-_A_Hard_Day%27s_Night/05_-_And_I_Love_Her.jams) file and I get the following error:

```
ParameterError: Unknown JAMS extension format: "jams"
```

I am pretty sure this file could be loaded with pyjams just a few weeks ago. Is there some problem with this specific JAMS file itself? The function can load properly files like [this](https://github.com/marl/jams-data/blob/master/datasets/SMC_MIREX/SMC_001.jams). 

If there's a problem with the file, the error should be more specific about why JAMS can't open it (the error message is clearly wrong, since `jams` should be a well-known format).

**Comment by urinieto** [comment]
The error was that the namespace `segment_isophonics` no longer exists (it is called `segment_open` now). We should fix the error message to correctly inform the user when this happens.

**Comment by bmcfee** [comment]
Oh, that's strange.  I think we must have the exception handler in the wrong spot or something.  I'll try to check it out.

**Comment by bmcfee** [comment]
84ebcced86fc3f6d0bfceebb97a61ef2b84b5055 should fix this.

The problem is that we were blindly accessing ``__NAMESPACE__[ns]`` with jams data, which causes a key error if the namespace is bad.  It now does a check first, and raises ``NamespaceError`` instead.

Guess I ought to write those unit tests for the ``ns`` module...

**Comment by urinieto** [comment]
Sweet, thanks. Closing it.
