### ISSUE TITLE
JAMS v2 Schema

### ISSUE THREAD

**Issue by justinsalamon** [marl/jams#5]
@ejhumphrey I've been snooping around the v2 schema, and wanted to discuss the [series type](https://github.com/marl/jams/blob/ver2/schema/jams_schema_v2.json#L49). 

1. If it has an array of of "values", why should it also have time and duration fields?
2. is there any way to identify what the series actually represents? i.e. how do I know if this is a time series or an frequency series?

**Comment by rabitt** [comment]
> https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L19 Why is duration a string here? I think we should stick to always measuring time in seconds, with the possible exception of UTC timestamp strings for file creation.

I agree that it should be a float.

> https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L41 Should we define a schema item for version fields? Here, we use string|number, elsewhere it's string+pattern.

+1

> https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L60 I've removed all type requirements for value fields. This might be a little dangerous, but it does allow us to pack arbitrary data keyed to (time, duration) values.

No issue here.

> Related to the above: should we do the same for confidence, allowing it to expand beyond a single number to a tuple which may be interpreted upstream? This would allow a practitioner to encode confidence for value, time, and/or duration without schematizing the semantics. Not sure if we want/need to allow this behavior. Use cases would be tremendously helpful here.

I'm trying to think of examples where confidence is more than just a single number... I can imagine a case where "confidence" is an array of confidence values (e.g. from a panel of experts-type system), but eh... 

> https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L62 I added a requirement that times and durations be non-negative. Do we really want this? Should it be enforced everywhere? I think probably yes, but a second opinion would be good.

In the Rock Corpus dataset, for example, I've seen pickup measures be notated with negative time (though, in this case, time was "global beat number", which isn't exactly time)

> https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L105 "Annotation.annotation_metadata" is a bit redundant. Can we simplify to "Annotation.metadata"?

I think this should stay as it is. The only "metadata" related fields are annotation_metadata and file_metadata. If you change one I'd change both, but It doesn't make sense to me to change file_metadata to metadata because it's ambiguous at the top level.

> In general, we should audit the required fields for consistency/sanity. I had to nix a few for debugging purposes, and am open to adding them back in.

Proceeding audit :
* https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L18 
What is "release"? I'd opt for a more specific name (e.g. dataset_release)
* https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L28
What is the difference between "corpus" and "data_source"?
* https://github.com/marl/jams/blob/pandas/schema/jams_schema.json#L173
source --> activation or source_activation

: audit complete.

**Comment by bmcfee** [comment]
> I'm trying to think of examples where confidence is more than just a single number... I can imagine a case where "confidence" is an array of confidence values (e.g. from a panel of experts-type system), but eh...

Example 1: confidence expressed as inter-quartile ranges (25th, 75th)-percentile
Example 2: simultaneous time and value confidence measurements.  Not sure where that would pop up, but it seems sensible.



> In the Rock Corpus dataset, for example, I've seen pickup measures be notated with negative time (though, in this case, time was "global beat number", which isn't exactly time)

Yes, I'd like to make a very clear distinction between "time"-typed measurements and all other values.  Beat numbers can be negative, no problem.

> I think this should stay as it is. The only "metadata" related fields are annotation_metadata and file_metadata. If you change one I'd change both, but It doesn't make sense to me to change file_metadata to metadata because it's ambiguous at the top level.

Good point. +1.

**Comment by bmcfee** [comment]
Scientific wild-assed guesses follow:

> What is "release"? I'd opt for a more specific name (e.g. dataset_release)

I believe this is inherited from [discogs](http://www.discogs.com/developers/#page:database,header:database-release) or [musicbrainz](https://musicbrainz.org/doc/MusicBrainz_Database/Schema#Release) schema, and corresponds to the track release, not the dataset.


> What is the difference between "corpus" and "data_source"?

I think "corpus" would be something like "Isophonics" or "RWC"; "data_source" would be "QMUL" or "AIST"?  @ejhumphrey care to clarify?



> source --> activation or source_activation

+1

**Comment by justinsalamon** [comment]
We originally based fields in annotation_metadata on: 
G. Peeters, K. Fort Towards A (Better) Definition Of The Description Of Annotated M.I.R. Corpora

There, they have a field called "origin", where example values include "synthetic", "experiment", "aggregation", "crowdsourcing", "game with a purpose" and "manual". I.e., the idea was to describe how the annotation data was generated.

I think that somewhere in history the term "origin" was deemed too ambiguous and replaced with "data_source". But yeah, I think that was the original purpose of that field...

**Comment by bmcfee** [comment]
This is starting to sound like the schema should be commented... :)

**Comment by bmcfee** [comment]
Note: turns out json doesn't allow comments.  laaaaaaaaaame!

Unrelated: I tweaked the FileMetadata.duration schema pattern yesterday to fix a couple of things:

* The expression was allowing minutes and seconds fields > 59
* it also had no provision for fractional seconds

Then I got to thinking... why is duration a string instead of a number measuring track duration in seconds?  Can we change it to be a number?

Time strings are slightly more human-readable than raw numbers, but they add considerable complexity to anything downline that wants to actually use the values.

**Comment by urinieto** [comment]
I would also like to have a float in seconds to represent duration. In
fact, that's what I have in MSAF. No idea why it is a string.

**Comment by bmcfee** [comment]
Another irksome thing: do we have a convention for encoding filenames in FileMetadata?  Does this belong in the identifiers sandbox, or should we promote it to a first-class property.

The use-case I'm thinking of is that many datasets have standardized layouts on disk (see: SMC, beatles_iso, MSD, etc etc etc), and since jams provides no handles for storing audio data itself, we should provide some way of linking back to the file on disk.

**Comment by bmcfee** [comment]
07804f08df75eb52165924367ef643efbbe95230 fixes the duration and adds content_path to the metadata.

> I understand the value of something like "content_path", but this gets a
> little janky if you start sharing annotations.

I don't see this as an issue, especially for annotations tied to specific corpora (eg, beatles_isophonics or cal500).  Presumably, every jams file will correspond to at least *some* audio file (or midi file, h5 file, whatever), whereas linked identifiers are a bit more open-ended.

We previously had no provision for linking back to the content source.  It could have been stuck in a sandbox along with identifiers, but we ( @rabitt and @justinsalamon ) discussed the point in the lab and agreed that source file path is a bit different from generic identifiers, and there should be a common way to access it.

I'm open to other solutions, but adding a content_path field to the metadata seemed like the simplest solution.

**Comment by ejhumphrey** [comment]
​simple solution, sure, but I don't think it's a permanent solution.
​There's no way to validate that the information is still true, and
filename drift is a thing.

**Comment by bmcfee** [comment]
> ​There's no way to validate that the information is still true, and
> filename drift is a thing.

Agreed.  I suppose this is what the identifiers sandbox is for, but that's a much bigger hammer for a small, but more frequent problem.

I guess the more general concern here is: how much stuff in jams is meant to be mutable, and how should we indicate it?

**Comment by ejhumphrey** [comment]
On Tue, Feb 3, 2015 at 6:24 PM, Brian McFee <notifications@github.com>
wrote:

> ​There's no way to validate that the information is still true, and
> filename drift is a thing.
>
> Agreed. I suppose this is what the identifiers sandbox is for, but that's
> a much bigger hammer for a small, but more frequent problem.
>
So, re: sponging local filepaths, maybe it's not the job of JAMS to do
that. Writing the filename into the JAMS object is no more stable or
reliable than telling someone to apply the same filebase to both the JAMS
file and the audio file to which it corresponds.
​This is information for a dataset manager, and I don't think JAMS is that
technology.​
​



> I guess the more general concern here is: how much stuff in jams is meant
> to be mutable, and how should we indicate it?
>
​I have a strong aversion to mutability, and I'd argue the only real
modifications a JAMS object should undergo are an append or merge. ​Curious
to hear any counterarguments.

**Comment by bmcfee** [comment]
> ​I have a strong aversion to mutability, and I'd argue the only real
> modifications a JAMS object should undergo are an append or merge. ​Curious
> to hear any counterarguments.

Ideally sure. But in reality, datasets always change. Probably it's the job of a VCS to manage this kind of thing.  (PSSSST: always version your data!)


> So, re: sponging local filepaths, maybe it's not the job of JAMS to do
> that. Writing the filename into the JAMS object is no more stable or
> reliable than telling someone to apply the same filebase to both the JAMS
> file and the audio file to which it corresponds.

Fair enough.

So.. would you object to using the identifiers sandbox for relative locations inside well-defined datasets?  My understanding is that these can always be augmented with additional identifiers as needed, and relative file path seems like a reasonable id for most existing datasets.

**Comment by bmcfee** [comment]
Hey folks: can we get a consensus on this content path issue?  The way I see it, we have three options for this functionality:

OPTION 1: schematized relative paths
  - add a field to `FileMetadata` to point form the jams object to a relative path within the collection
  - example: in isophonics, you might have have `jam.file_metadata.content_path == 'audio/The Beatles/01_-_Please_Please_Me/01_-_I_Saw_Her_Standing_There.flac'`
  - Pro: easy access.  Makes intuitive sense for many existing corpora.
  - Con: rigid. would be unwieldy for data that has no unique source (ie, lives in multiple collections)

OPTION 2: sandboxed relative paths
  - Like the above, but `content_path` would be a sandbox variable, ie, outside of the schema.
  - example: `jam.file_metadata.sandbox.content_path == 'audio/The Beatles/01_-_Please_Please_Me/01_-_I_Saw_Her_Standing_There.flac'`
  - Pro: more flexible than option 1, but does basically the same thing.  Fits the existing style for cross-referencing identifiers (eg, musicbrainz or echo nest).
  - Con: could become a de facto standard, rather than an official standard, for accessing content through jams.  No way to enforce consistency of use across datasets.

OPTION 3: punt upstream to a proper database
  - Provide no functionality for indexing content within a jams.  Instead, rely on an upstream database to provide the mapping.
  - Pro: makes our lives (as jams developers) easier
  - Con: makes usage more difficult, especially for one-off projects that lack proper database infrastructure.

Votes?

**Comment by bmcfee** [comment]
PS: my vote is to support 2 in our conversion scripts, but encourage 3 whenever possible.  The two need not be incompatible.

**Comment by justinsalamon** [comment]
+1 for option 2. If it *does* becomes a de-facto standard further down the line we can consider incorporating it in the schema in a future release, but yeah, not sure I'd make it a rigid part of the schema right now.

**Comment by urinieto** [comment]
Also like 2 better.

**Comment by bmcfee** [comment]
Sounds like option 2 is the winner.  @ejhumphrey : you agree?

**Comment by ejhumphrey** [comment]
Apologies for delays, been in the woods for the last few days.

Generally on board with 2. How do we feel about
jam.file_metadata.sandbox.content_path vs jam.sandbox.content_path ?

**Comment by bmcfee** [comment]
> jam.sandbox.content_path

+1

**Comment by ejhumphrey** [comment]
i digz

**Comment by bmcfee** [comment]
Done and done.

Anything else remaining, or shall we close this issue?

**Comment by bmcfee** [comment]
once more: can we close this one?

**Comment by ejhumphrey** [comment]
uh, sure?

**Comment by justinsalamon** [comment]
looks like it yeah
