### ISSUE TITLE
Get approximate duration?

### ISSUE THREAD

**Issue by urinieto** [marl/jams#68]
Do we have a function to get the approximate duration of a track by averaging the last segment boundaries (and/or other relevant information) from all the available annotators?

If not, it might be helpful to include it, maybe in the utils module.

(I feel I implemented that function at some point, but can't remember where...)

**Comment by bmcfee** [comment]
I'm not sure that we should make this sort of thing easy to do.  I can imagine it being abused and leading to a propagation of timing errors from imperfect annotations (see: isophonics).  Also, given #67, partial annotations could complicate this a lot.

I agree that it would be nice to have a quick way to get the track duration, but it really ought to come from audio, not annotations.  Otherwise, why have the field in the first place?

**Comment by urinieto** [comment]
Ok, I see your point. I will close this issue, unless anyone still feels strongly about having this included in jams.

**Comment by urinieto** [comment]
In case someone needs something like this: https://github.com/urinieto/msaf/blob/jams/datasets/parsers/jams2_to_jams.py#L62-L84

Closing this.
